---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
  - id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_tflint
  - id: terraform_tfsec
  - id: terraform_docs
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.30.0
  hooks:
  - id: yamllint
    args: [-d, relaxed, --format, parsable]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150']
