apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vaultpkisecret-tls
  namespace: tenant-1
# https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#vaultpkisecretspec
spec:
  # If no value is specified the Operator will default to the default VaultAuth,
  # configured in its own Kubernetes namespace.
  vaultAuthRef: default
  # Namespace of the vaultauth
  # namespace: tenant-1
  mount: pki
  commonName: nginx
  role: default
  destination:
    create: true
    name: pki-tls
    type: kubernetes.io/tls
  commonName: localhost
  format: pem
  revoke: true
  clear: true
  expiryOffset: 15s
  ttl: 1m
