apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  namespace: loki
data:
  rules.yaml: |
    groups:
      - name: vault-requests
        rules:
          - record: vault:requests:rate1m
            expr: |
              sum(rate({application="vault"} |~ "\"type\":\"request\"" [1m]))
