apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  namespace: loki
data:
  rules.yaml: |
    groups:
      - name: vault-requests
        rules:
          - alert: HighPercentageVaultRequests
            expr: |
              sum(rate({application="vault"} |~ "\"type\":\"request\"" [1m])) >= 0
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: High percentage of Vault requests
          - record: vault:requests:rate1m
            expr: |
              sum(rate({application="vault"} |~ "\"type\":\"request\"" [1m]))